### ISSUE TITLE
Entire Word Guess

### ISSUE THREAD

**Issue by ecarnohan** [ucsb-cs56-projects/cs56-games-hangman#23]
Add the ability to guess the entire word instead of just one letter. Players may not guess multiple letters unless the guess is the same number of letters as the word.

Estimated Points: 200

**Comment by jrcryan** [comment]
~200 points

**Comment by arda-** [comment]
Feature has been added, but some invalid character filtering bugs remain (see issue #33)

**Comment by arda-** [comment]
reopening issue because @zzeng and @makhamzadeh want to work on an older version of the repo and  implement their own fix

**Comment by arda-** [comment]
Feature has been added, but some invalid character filtering bugs remain (see issue #33)

**Comment by MadRubicant** [comment]
Invalid words are not accepted, but invalid characters are. It appears that any UTF-16 string with a length of 2 bytes is accepted. 

50 pts

**Comment by MadRubicant** [comment]
F16 OK (50 pts)

**Comment by brianslee** [comment]
Apparently is a feature. Fixed
