### ISSUE TITLE
Specific Color Options in Options Menu

### ISSUE THREAD

**Issue by triptisinghal** [UCSB-CS56-Projects/cs56-games-hangman#28]
Add a feature in the options menu for the user to be able to select a specific color for the background and the hangman image. This would be in addition to the game's ability to generate a random color for background and hangman.

**Comment by jrcryan** [comment]
approved
~100 points

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by YunSuk** [comment]
Resolved
