### ISSUE TITLE
Fix "Hints" button small bug

### ISSUE THREAD

**Issue by ecarnohan** [UCSB-CS56-Projects/cs56-games-hangman#29]
Currently, when the player tries to click "Hints" in between rounds of the game, the program will crash. Make the Hints button un-clickable during this state of play.

**Comment by jrcryan** [comment]
approved
~50 points

**Comment by arda-** [comment]
Another bug: clicking hint after a round ends spends the hint on the word that was already revealed.

**Comment by arda-** [comment]
fixed!
