### ISSUE TITLE
Celebrate the Win!

### ISSUE THREAD

**Issue by ecarnohan** [UCSB-CS56-Projects/cs56-games-hangman#30]
Make something cool happen when the player wins the game.

Ideas include:
-Make the hangman jump off the gallows
-Make an animation that says "Congratulations!" or something of that sort

**Comment by jrcryan** [comment]
approved
~50 points

**Comment by MadRubicant** [comment]
F16 OK (50 pts)

**Comment by MadRubicant** [comment]
Resolved
