### ISSUE TITLE
Full Phrase Guesses

### ISSUE THREAD

**Issue by ecarnohan** [ucsb-cs56-projects/cs56-games-hangman#31]
Include an option to guess full phrases instead of just single words.

**Comment by jrcryan** [comment]
approved
~100 points

**Comment by arda-** [comment]
Works!

**Comment by arda-** [comment]
Oops, confused this issue with "full word guesses" – different from _phrases_.

**Comment by MadRubicant** [comment]
Reassessing at 200 pts - phrases would require more chances than single words

**Comment by MadRubicant** [comment]
F16 OK (200 pts)

**Comment by brianslee** [comment]
apparently fixed. Closing issue. W18
