### ISSUE TITLE
consolidate and sort resources

### ISSUE THREAD

**Issue by arda-** [UCSB-CS56-Projects/cs56-games-hangman#32]
While there is currently a resources folder, many image assets are in the main repo folder. Organize them all into resources, and proper subfolders (/audio/, /img/, etc).

Be sure to update any of the code's dependencies on the images' paths.

50 points

**Comment by MadRubicant** [comment]
F16 OK (50 pts)

**Comment by MadRubicant** [comment]
Resolved
