### ISSUE TITLE
tests do not pass

### ISSUE THREAD

**Issue by zzeng** [UCSB-CS56-Projects/cs56-games-hangman#35]
The ant tests do not pass. We need to make sure that the ant tests will pass.

**Comment by arda-** [comment]
approved, 100 points

**Comment by MadRubicant** [comment]
The unit tests for this project are overly monolithic. Split them up into units. 

150 pts

**Comment by MadRubicant** [comment]
F16 OK (150 pts)

**Comment by MadRubicant** [comment]
Resolved
