### ISSUE TITLE
Implement an online two player option

### ISSUE THREAD

**Issue by makhamzadeh** [ucsb-cs56-projects/cs56-games-hangman#48]
To make it work over the network I would suggest importing into https://github.com/UCSB-CS56-Projects/cs56-games-client-server-v2

300 points to import into that project and make functional.

**Comment by arda-** [comment]
W16 OK

**Comment by MadRubicant** [comment]
F16 OK (300 pts)

**Comment by brianslee** [comment]
Online mode has been implemented. Closing W18
