### ISSUE TITLE
clicking on "hint" button between rounds reduces points

### ISSUE THREAD

**Issue by arda-** [ucsb-cs56-projects/cs56-games-hangman#50]
Hint button should be deactivated between rounds - clicking hint reduces up to 3 points between rounds.

75 points.

**Comment by MadRubicant** [comment]
Pressing the Hint button between rounds causes the game to freeze. 

100 pts

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by MadRubicant** [comment]
This is less buggy than before, but still a little broken.

**Comment by brianslee** [comment]
Appears fixed. Closed for Now. W18
