### ISSUE TITLE
Opening the option menu twice causes a window to be orphaned

### ISSUE THREAD

**Issue by aermakovucsb** [UCSB-CS56-Projects/cs56-games-hangman#61]
If you open an options window and then click back to the main window and press the options button again it causes the previous options window to be orphaned. The orphaned window does not respond to button presses and can not be closed using the finish or cancel buttons. ~100 points

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by YunSuk** [comment]
Seems to be resolved
