### ISSUE TITLE
Crash for runCLI

### ISSUE THREAD

**Issue by YunSuk** [ucsb-cs56-projects/cs56-games-hangman#67]
Sometimes runCLI crashes with following error:

compile:

runCLI-noarg:
     [echo] 
     [echo] To run with your own word list file, you can type `ant run -Darg0="YourFileName"`
     [echo] You can also use "Enter" key instead of clicking a "Submit" button.
     [echo]     
     [java] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7
     [java] 	at edu.ucsb.cs56.projects.games.hangman.HangmanCLI.getGallows(HangmanCLI.java:100)
     [java] 	at edu.ucsb.cs56.projects.games.hangman.HangmanCLI.play(HangmanCLI.java:40)
     [java] 	at edu.ucsb.cs56.projects.games.hangman.CLIMain.main(CLIMain.java:34)
     [java] Java Result: 1

runCLI-witharg:

runCLI:

BUILD SUCCESSFUL
Total time: 0 seconds

The word list used from WordsList.txt:
Object-Oriented
Interface
Class
Attribute
Static Variable

Try to find why this error is happening and fix it.

200 points

**Comment by brianslee** [comment]
W18 Ok 200 Points
