### ISSUE TITLE
Initial Multiplayer Implementation

### ISSUE THREAD

**Issue by brjohnson61** [UCSB-CS56-Projects/cs56-games-hangman#74]
Multiplayer: Creates two connected game instances where two players can choose the word for the other player to guess. To win, the player guesses the opponents word correctly. If the player cannot guess their opponents word, they lose. The game is run from two separate computers. This is not a race; we can all be winners. Limited to two players but can be extended to more.

Mulyiplayer Workflow: One player hosts the games server, and one player joins the game server.
     MainMenu -> Multiplayer ->Host or Join -> Enter server details -> socket connection and game instantiation. 

SinglePlayerWorkflow: Play the game by yourself, guessing words from a wordList.
MainMenu -> SinglePlayer -> Game instantiation

(Code design: 200 PTS)

Features Added:

- Main Menu: Takes wordList argument from build.xml and lets user choose between single player and multiplayer. <PTS: 50>

- Multiplayer Menu: Asks user if they would like to create server or join server. <PTS: 50>

- HostServer: Creates GUI for making a socket, displays ipAddress to connect to, picks opponent's word, and displays status message. <PTS: 75>

- JoinServer: Creates GUI that takes in IP address of host, opponent's word, server port number, and displays status message as well as error message, when a server is not there, which restarts the join game process. <PTS: 75>

Features Modified:

- Created a new HangmanGUI constructor that allows a new hangman game based on a string instead of a wordList. <PTS: 100>

  - Added a new private boolean variable to HangmanGUI called "isMultiplayer".

  - Removed wordList from the multiplayer aspect of the game.

- Modified the RESTART button in multiplayer to bring you back to the main menu, instead of picking a new single player word from the wordList. <PTS: 50>

Total: 600 PTS

**Comment by YunSuk** [comment]
Ok. F17
