### ISSUE TITLE
Hint Limit

### ISSUE THREAD

**Issue by brjohnson61** [ucsb-cs56-projects/cs56-games-hangman#76]
In its current state, the Hangman game allows you to click the hint button quite a lot, making it virtually impossible to lose.  

This issue gives points to splice in another menu after "Single Player" has been chosen that allows you to select the difficulty.  A higher difficulty would reduce the number of available hints significantly, and easy difficulty would have no limit.

**Comment by YunSuk** [comment]
F17 OK. 200 points

**Comment by brianslee** [comment]
W18 Ok. 200 Points

**Comment by brianslee** [comment]
Tentatively fixed. Might want to adjust to make difficulty scale.
W18 Closed
