### ISSUE TITLE
Factor out Options menu code.

### ISSUE THREAD

**Issue by brjohnson61** [ucsb-cs56-projects/cs56-games-hangman#79]
In its current state, the Options Button is handled in HangmanGUI and the logic for creating the options GUI and the features it enables are also implemented in HangmanGUI.java.  This is poor programming style, and makes HangmanGUI.java a confusing mess.  This issue would work towards refactoring HangmanGUI as a whole by creating a new class called "OptionsMenu.java", or other descriptive name.  Similar point amounts would be given for other menu items to be fixed in this way.

**Comment by YunSuk** [comment]
F17 OK. 200 points

**Comment by brianslee** [comment]
W18 Ok 200 Points

**Comment by brianslee** [comment]
Fixed.
W18 Closed
