### ISSUE TITLE
Adding a "Back" button

### ISSUE THREAD

**Issue by brjohnson61** [ucsb-cs56-projects/cs56-games-hangman#80]
Fixing this issue would add a "back" button to all menus that returns you to the previous menu.  This would allow significantly more user control over the game.

**Comment by YunSuk** [comment]
F17 OK. 150 points.

**Comment by brianslee** [comment]
W18 Ok. 150 Points

**Comment by brianslee** [comment]
Implemented.
W18 Closed.
